# # GPIO for IR beam and servo
# CONFIG_GPIO=y

# # Serial and console
# CONFIG_SERIAL=y
# CONFIG_CONSOLE=y
# CONFIG_PRINTK=y
# CONFIG_STDOUT_CONSOLE=y

# # State machine framework
# CONFIG_SMF=y

# # Shell
# CONFIG_SHELL=y
# # CONFIG_SHELL_BACKEND_SERIAL=y

# # Logging
# CONFIG_LOG=y

# # PWM for servo (when ready)
# CONFIG_PWM=y

# # GPIO
# CONFIG_GPIO=y

# # PWM
# CONFIG_PWM=y

# # Storage
# CONFIG_NVS=y
# CONFIG_FLASH=y
# CONFIG_FLASH_MAP=y

# # State machine
# CONFIG_SMF=y

# GPIO
CONFIG_GPIO=y

# PWM
CONFIG_PWM=y

# Storage
CONFIG_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

# State machine
CONFIG_SMF=y

# USB CDC ACM console
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
CONFIG_UART_LINE_CTRL=y

# Console
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y

# Shell
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y

# Disable RTT
CONFIG_USE_SEGGER_RTT=n

# FLAGS BEFORE THIS ARE REQUIRED FOR THE DEVICE TO FUNCTION, FLAGS AFTER THIS ARE FOR WIFI

# ESP32 driver 
CONFIG_WIFI=y
CONFIG_NET_L2_WIFI=y
CONFIG_ESP_AT=y
CONFIG_NET_IPV4=y
CONFIG_NET_DHCPV4=y
CONFIG_DNS_RESOLVER=y

# Networking stack (required for WiFi mgmt API)
CONFIG_NETWORKING=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_MGMT_EVENT_STACK_SIZE=1024
CONFIG_NET_DRIVERS=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y